# Generated by Django 5.2.14 on 2026-06-02 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(db_index=True, max_length=20, verbose_name='등록번호')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='성명')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='나이')),
                ('sex', models.CharField(blank=True, choices=[('F', 'F'), ('M', 'M'), ('O', 'O')], max_length=1, verbose_name='성별')),
                ('prescription_date', models.DateField(blank=True, null=True, verbose_name='처방일자')),
                ('prescription_code', models.CharField(choices=[('간단', '도수치료 간단'), ('기본', '도수치료 기본'), ('복잡', '도수치료 복잡')], default='간단', max_length=4, verbose_name='처방코드')),
                ('is_outpatient', models.BooleanField(default=True, verbose_name='외래(외)')),
                ('memo', models.CharField(blank=True, max_length=255, verbose_name='환자 메모')),
                ('department', models.CharField(blank=True, default='재활의학과', max_length=50, verbose_name='진료과')),
                ('status', models.CharField(choices=[('대기중', '대기중'), ('예약완료', '예약완료'), ('시행중', '시행중'), ('종결', '종결')], db_index=True, default='대기중', max_length=4, verbose_name='상태')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='연락처')),
                ('preferred_days', models.CharField(blank=True, max_length=50, verbose_name='희망요일')),
                ('preferred_times', models.CharField(blank=True, max_length=50, verbose_name='희망시간')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
                ('last_contact_date', models.DateField(blank=True, null=True, verbose_name='마지막연락일')),
                ('contact_result', models.CharField(blank=True, max_length=255, verbose_name='연락결과')),
                ('target_sessions', models.IntegerField(default=6, verbose_name='종결 목표 회차')),
                ('completion_eval_date', models.DateField(blank=True, null=True, verbose_name='종결평가 예정일')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='도수 시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='도수 종결일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-prescription_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slots', models.JSONField(default=list, verbose_name='시간대 구성')),
            ],
            options={
                'verbose_name': '설정',
                'verbose_name_plural': '설정',
            },
        ),
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='이름')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('order', models.IntegerField(default=0, verbose_name='정렬')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='실시일')),
                ('number', models.IntegerField(verbose_name='회차')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='scheduler.patient')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='therapist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='scheduler.therapist', verbose_name='담당치료사'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, '월'), (1, '화'), (2, '수'), (3, '목'), (4, '금')], verbose_name='요일')),
                ('slot_index', models.IntegerField(verbose_name='시간대 인덱스')),
                ('is_fixed', models.BooleanField(default=False, verbose_name='스케줄 고정')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='scheduler.patient')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='scheduler.therapist')),
            ],
            options={
                'ordering': ['weekday', 'slot_index'],
                'constraints': [models.UniqueConstraint(fields=('therapist', 'weekday', 'slot_index'), name='unique_slot_per_therapist')],
            },
        ),
    ]
