# Generated by Django 5.2.14 on 2026-06-09 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_seed_therapists'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='category',
            field=models.CharField(blank=True, choices=[('lumbar1', 'Lumbar phase1'), ('lumbar2', 'Lumbar phase2'), ('lumbar3', 'Lumbar phase3'), ('cervical', 'Cervical'), ('shoulder1', 'Shoulder phase1'), ('shoulder2', 'Shoulder phase2'), ('shoulder3', 'Shoulder phase3'), ('etc', '기타')], max_length=10, verbose_name='부위/단계'),
        ),
        migrations.AddField(
            model_name='patient',
            name='category_etc',
            field=models.CharField(blank=True, max_length=100, verbose_name='부위/단계(기타)'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, '월'), (1, '화'), (2, '수'), (3, '목'), (4, '금')], verbose_name='요일')),
                ('period', models.IntegerField(choices=[(0, '오전'), (1, '오후')], verbose_name='시간대')),
                ('order', models.IntegerField(default=0, verbose_name='순번')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='scheduler.patient')),
            ],
            options={
                'ordering': ['weekday', 'period', 'order', 'created_at'],
            },
        ),
    ]
