# Generated by Django 5.2.14 on 2026-06-09 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_patient_category_patient_category_etc_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrelimSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='실시일')),
                ('number', models.IntegerField(verbose_name='회차')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prelim_sessions', to='scheduler.patient')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
