# Generated by Django 5.2.14 on 2026-06-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_prelimsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='external_sessions',
            field=models.IntegerField(default=0, verbose_name='타병원 기시행 횟수'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='target_sessions',
            field=models.IntegerField(default=15, verbose_name='연간 도수 한도(회)'),
        ),
    ]
